# Generated by Django 5.0.2 on 2026-02-25 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phases', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('form_data', models.JSONField(verbose_name='Datos del Formulario')),
                ('generated_prompt', models.TextField(verbose_name='Prompt Generado')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phases.innovationphase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='projects.project')),
            ],
            options={
                'verbose_name': 'Respuesta de Fase',
                'verbose_name_plural': 'Respuestas de Fases',
            },
        ),
    ]
