# Generated by Django 5.0.2 on 2026-02-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_alter_phaseresponse_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phaseresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='phaseresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
