# Generated by Django 5.0.2 on 2026-02-25 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('title', models.CharField(max_length=255, verbose_name='Título de la Fase')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Fase de Innovación',
                'verbose_name_plural': 'Fases de Innovación',
            },
        ),
        migrations.CreateModel(
            name='PhaseField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Etiqueta del Campo')),
                ('field_name', models.SlugField(help_text="Nombre técnico (ej: 'idea_principal').", max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Texto Corto'), ('textarea', 'Texto Largo'), ('number', 'Número')], default='text', max_length=20, verbose_name='Tipo de Campo')),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True, verbose_name='Placeholder')),
                ('required', models.BooleanField(default=True, verbose_name='Obligatorio')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='phases.innovationphase')),
            ],
            options={
                'verbose_name': 'Campo de Formulario',
                'verbose_name_plural': 'Campos de Formulario',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PromptChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Contenido del Fragmento')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Es Opcional')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_chunks', to='phases.innovationphase')),
            ],
            options={
                'verbose_name': 'Fragmento de Prompt',
                'verbose_name_plural': 'Fragmentos de Prompt',
                'ordering': ['order'],
            },
        ),
    ]
