# Generated by Django 5.0.2 on 2026-02-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='innovationphase',
            options={'ordering': ['order'], 'verbose_name': 'Fase de Innovación', 'verbose_name_plural': 'Fases de Innovación'},
        ),
        migrations.AddField(
            model_name='innovationphase',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='phasefield',
            name='list_of_options',
            field=models.JSONField(blank=True, null=True, verbose_name='Lista de opciones'),
        ),
        migrations.AlterField(
            model_name='innovationphase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='innovationphase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='phasefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Texto Corto'), ('number', 'Número'), ('boolean', 'Booleano'), ('dropdown', 'Desplegable'), ('multi-select', 'Selección Múltiple')], default='text', max_length=20, verbose_name='Tipo de Campo'),
        ),
    ]
