# Generated by Django 5.0.2 on 2026-02-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0002_alter_innovationphase_options_innovationphase_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovationphase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='innovationphase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
